import os
import glob
import csv
import numpy as np
import matplotlib.pyplot as plt
import json
import warnings

# Try importing the unfolding and masking functions
try:
    from band_unfolding import unfold_bands, trim_above_light_cone
    HAS_UNFOLDING = True
except ImportError:
    HAS_UNFOLDING = False

# ===================================================================
# Configuration
# ===================================================================

# Target band to visualize across the sweep
target_band = 4  # Change this to 4, 5, or 6 depending on your target slow-light band

# Specify the CSV file generated by run_sweep_simp_3d_gc.py
# Leave as empty string '' to automatically find the newest sweep CSV in output/
csv_file = '' 

apply_unfolding = True         # Apply anti-crossing band unfolding
apply_lightcone_mask = True    # Mask (set NaN) data above the light cone

def find_latest_csv():
    list_of_files = glob.glob('output/sweep_3d_*.csv')
    if not list_of_files:
        return None
    latest_file = max(list_of_files, key=os.path.getmtime)
    return latest_file

def main():
    global csv_file
    if not csv_file:
        csv_file = find_latest_csv()
        if not csv_file:
            print("No CSV file found in output/ directory. Please run the sweep script first.")
            return
    
    print(f"Loading sweep data from: {csv_file}")
    
    sweep_param_name = ""
    sweeps = []
    
    # Read the summary CSV file to get cache paths and sweep values
    with open(csv_file, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            sweep_param_name = row['Sweep_Param']
            sweeps.append({
                'val': float(row['Value']),
                'cache_file': row['Cache_File']
            })
            
    if not sweeps:
        print("No sweep data found in the CSV.")
        return

    # Create figure with two subplots: band dispersion (f vs k) and group index (ng vs lambda)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

    global_f_min = np.inf
    global_f_max = -np.inf
    last_k = None
    last_n_clad = 1.44

    for sweep in sweeps:
        val = sweep['val']
        npz_path = sweep['cache_file']
        
        if not os.path.exists(npz_path):
            print(f"Warning: Cache file {npz_path} not found. Skipping.")
            continue
            
        npz = np.load(npz_path, allow_pickle=True)
        k = npz['k_x']
        last_k = k
        
        # Determine the key for frequencies
        if 'freqs' in npz:
            freqs = npz['freqs'].copy()
        elif 'freqs_te' in npz:
            freqs = npz['freqs_te'].copy()
        elif 'freqs_even' in npz:
            freqs = npz['freqs_even'].copy()
        else:
            print(f"Could not find frequency data in {npz_path}. Skipping.")
            continue
            
        info = json.loads(str(npz['params_json']))
        a_nm = info['a_nm']
        n_clad = info.get('n_SiO2', 1.44)
        last_n_clad = n_clad
        
        # Apply anti-crossing unfolding and light-cone masking
        if HAS_UNFOLDING:
            if apply_unfolding:
                freqs, _ = unfold_bands(freqs, k)
            if apply_lightcone_mask:
                freqs = trim_above_light_cone(freqs, k, n_clad)
                
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            wl_nm = a_nm / freqs
            
        if target_band >= freqs.shape[1]:
            print(f"Band {target_band} not available in {npz_path}.")
            continue
            
        f_b = freqs[:, target_band]
        valid_idx = ~np.isnan(f_b)
        
        if not np.any(valid_idx):
            print(f"Warning: Band {target_band} is completely NaN for {sweep_param_name}={val} (all above light cone).")
            continue
            
        f_valid = f_b[valid_idx]
        k_valid = k[valid_idx]
        wl_valid = wl_nm[valid_idx, target_band]
        
        if np.nanmin(f_valid) < global_f_min: global_f_min = np.nanmin(f_valid)
        if np.nanmax(f_valid) > global_f_max: global_f_max = np.nanmax(f_valid)

        # 1. Plot band dispersion
        ax1.plot(k_valid, f_valid, label=f"{sweep_param_name} = {val:.3f}")
        
        # 2. Calculate and plot group index ng
        vg = np.gradient(f_valid, k_valid)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            ng = np.abs(-1.0 / vg)
            
        ax2.plot(wl_valid, ng, label=f"{sweep_param_name} = {val:.3f}", marker='.', markersize=4)

    # ---------------------------------------------------------
    # Subplot 1 formatting (Dispersion)
    # ---------------------------------------------------------
    if last_k is not None:
        light_line = last_k / last_n_clad
        ax1.plot(last_k, light_line, 'k--', lw=1.0, label=f'light line (n={last_n_clad})')
        ax1.fill_between(last_k, light_line, light_line.max() * 1.5, color='lightyellow', alpha=0.6)
        
    ax1.set_xlabel('k (2π/a)')
    ax1.set_ylabel('Freq (a/λ)')
    ax1.set_title(f'Band {target_band} Dispersion')
    if not np.isinf(global_f_min) and not np.isinf(global_f_max):
        ax1.set_ylim(global_f_min * 0.95, global_f_max * 1.05)
    ax1.grid(True)
    ax1.legend()
    
    # ---------------------------------------------------------
    # Subplot 2 formatting (Group Index)
    # ---------------------------------------------------------
    ax2.set_xlabel('Wavelength λ (nm)')
    ax2.set_ylabel('Group Index $n_g$')
    ax2.set_title(f'Band {target_band} Group Index')
    ax2.set_ylim(0, 40)  # Common viewing window for slow light
    ax2.grid(True)
    ax2.legend()
    
    # Optional: Highlight target slow light area
    ax2.axhspan(5.0, 7.0, alpha=0.15, color='green', label='Target ng (5~7)')
    ax2.axvline(1550, color='blue', ls=':', lw=0.8, label='1550nm')
    # Use ax2.legend() again if we want to show these new patches, or skip for brevity.

    fig.suptitle(f"Parameter Sweep: {sweep_param_name} (Focusing on Band {target_band})", 
                 fontsize=14, fontweight='bold')
    
    plt.tight_layout()
    fig.subplots_adjust(top=0.90)  # leave space for suptitle
    
    # Optionally save to file
    # plt.savefig(f"output/sweep_plot_{sweep_param_name}_band{target_band}.png", dpi=150)
    plt.show()

if __name__ == '__main__':
    main()